# -*- coding: utf-8 -*-
"""414_Final_Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmHl7t5MvuuajxuBRgYEVPxWJQjnUsdA
"""

#Importing all necessary packages
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

#Loading car dataset
df = pd.read_csv("sport_car_prices_cleaned.csv")
#Dropping rows that have missing values in these categories
df = df.dropna(subset=['Horsepower', 'Torque (lb-ft)', '0-60 MPH Time (seconds)', 'Price (in thousands of dollars)'])
df = df.drop_duplicates(subset=['Car Make', 'Car Model'])
df = df.reset_index(drop=True)


#Exploring the dataset
df

#Scaling the features
features = ['Horsepower', 'Torque (lb-ft)', '0-60 MPH Time (seconds)', 'Price (in thousands of dollars)']
scaled = StandardScaler().fit_transform(df[features])

#Computing cosine similarity matrix
sim_matrix = cosine_similarity(scaled)

#Creating a function to find top 10 similar cars for a given model name
def get_top10(model_name):
    # Case-insensitive exact match
    match = df[df['Car Model'].str.lower() == model_name.lower()]
    if match.empty:
        print(f"'{model_name}' not found in dataset.")
        return None

    idx = match.index[0]
    query_make = df.loc[idx, 'Car Make']

    scores = list(enumerate(sim_matrix[idx]))
#Excluding the query car itself AND other cars with the same make + overlapping model name
    scores = [
        (i, s) for i, s in scores
        if i != idx and not (
            df.loc[i, 'Car Make'] == query_make and
            model_name.lower() in str(df.at[i, 'Car Model']).lower()
        )
    ]
    scores.sort(key=lambda x: x[1], reverse=True)

    top10 = scores[:10]
    results = df.loc[[i for i, _ in top10], ['Car Make', 'Car Model']].copy()
    results['Similarity Score'] = [round(s, 4) for _, s in top10]
    results = results.reset_index(drop=True)
    return results

#Doing the actual analysis
queries = ['Mustang GT', 'WRX STI', '370Z']

for q in queries:
    print(f"\nTop 10 similar cars to: {q}")
    print("-" * 40)
    result = get_top10(q)
    if result is not None:
        print(result.to_string(index=False))

#Creating visualizations
mustang = get_top10('Mustang GT')
if mustang is not None:
    labels = mustang['Car Make'] + ' ' + mustang['Car Model']
    plt.figure(figsize=(10, 6))
    plt.barh(labels[::-1], mustang['Similarity Score'][::-1], color='steelblue')
    plt.xlabel('Similarity Score')
    plt.title('Top 10 Cars Similar to Ford Mustang GT')
    plt.tight_layout()
    plt.savefig('mustang_gt_similarity.png', dpi=150)
    plt.show()

"""***Project Extension***"""

#The Elbow Method to determine optimal k
wcss = []
cluster_range = range(1, 11)

for k in cluster_range:
    kmeans = KMeans(n_clusters=k, init='k-means++', random_state=42)
    kmeans.fit(scaled)
    wcss.append(kmeans.inertia_)

#Plotting the Elbow Curve
plt.figure(figsize=(8, 5))
plt.plot(cluster_range, wcss, marker='o', linestyle='--', color='darkblue')
plt.title('The Elbow Method for Optimal Optimal Clusters (k)')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('WCSS (Inertia)')
plt.xticks(cluster_range)
plt.grid(True, linestyle=':', alpha=0.6)
plt.tight_layout()
plt.savefig('elbow_method.png', dpi=150)
plt.show()

#Fit K-Means with the chosen number of clusters
optimal_k = 3
kmeans_model = KMeans(n_clusters=optimal_k, init='k-means++', random_state=42)
df['Cluster'] = kmeans_model.fit_transform(scaled).argmax(axis=1)

#Visualizing the Clusters (Horsepower vs. Price)
plt.figure(figsize=(10, 6))
colors = ['teal', 'tomato', 'orange']

for cluster_id in range(optimal_k):
    cluster_data = df[df['Cluster'] == cluster_id]
    plt.scatter(
        cluster_data['Horsepower'],
        cluster_data['Price (in thousands of dollars)'],
        c=colors[cluster_id],
        label=f'Cluster {cluster_id}',
        alpha=0.7,
        edgecolors='w',
        s=60
    )

plt.title('Sports Car Market Segmentation via K-Means Clustering')
plt.xlabel('Horsepower')
plt.ylabel('Price (in thousands of dollars)')
plt.legend()
plt.grid(True, linestyle=':', alpha=0.5)
plt.tight_layout()
plt.savefig('market_clusters.png', dpi=150)
plt.show()

#Printing Summary Profiles of the Clusters
print("\n" + "="*50)
print("CLUSTER PERFORMANCE PROFILES (MEANS)")
print("="*50)
cluster_profiles = df.groupby('Cluster')[features].mean().round(2)
print(cluster_profiles)